### ISSUE TITLE
Paginated models should be defined by the gem user, instead of hardcoded

### ISSUE THREAD

**Issue by jeroenrietveld** [hoppinger/wp-connector#33]
https://github.com/hoppinger/wp-connector/blob/master/app/models/concerns/wp_cache.rb#L119

**Comment by sebastiaandegeus** [comment]
This is fixed in the branch:  https://github.com/hoppinger/wp-connector/blob/feature/fixed_paginated_models/app/models/concerns/wp_cache.rb
